Algoritmo "contadorPessoas"

Var
   S, R, resp: caractere
   cont, I, CC, Ho, Mu: inteiro

Inicio
Repita
      Escreval("Qual o sexo? [M/F]")
      Leia(S)
      Escreval("Qual a idade? ")
      Leia(I)
      Escreval("Qual a cor do cabelo?")
      Escreval("----------------------")
      Escreval("[1] Preto")
      Escreval("[2} Castanho")
      Escreval("[3] Ruivo")
      Escreval("[4] Loiro")
      Leia(CC)
      Escreval("Quer continuar? [S/N]")
      Leia(R)
      LimpaTela
Ate R = "N"



Fimalgoritmo